services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-53306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DB:-dbop}"
      MYSQL_USER: "${MYSQL_USER:-dbop}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-dbop}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
      interval: 2s
      timeout: 5s
      retries: 30

